name:                tlamodel
version:             0.9.11
github:              "craft095/tlamodel"
license:             BSD3
author:              "Dmitry Kulagin"
maintainer:          "dmitry.kulagin@gmail.com"
copyright:           "2021 Dmitry Kulagin"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/craft095/tlamodel#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - directory
  - filepath
  - megaparsec
  - mtl
  - text

executables:
  tlamodel:
    main:                Main.hs
    source-dirs:         app
    other-modules:       Paths_tlamodel
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - tlamodel

tests:
  tlamodel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - file-embed
    - megaparsec
    - text
    - tlamodel
