name:                tlatpl
version:             0.1.0
github:              "craft095/tlatpl"
license:             BSD3
author:              "Dmitry Kulagin"
maintainer:          "dmitry.kulagin@gmail.com"
copyright:           "2021 Dmitry Kulagin"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/craft095/tlatpl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - directory
  - megaparsec
  - mtl
  - text

executables:
  tlatpl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - tlatpl

tests:
  tlatpl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - megaparsec
    - text
    - tlatpl
